import type { Metadata } from "next";
import "./globals.css";
import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
      >
        <div className="bg-background relative z-10 flex min-h-svh flex-col">
            <ThemeProvider>
              <SiteHeader />
                {children}
            </ThemeProvider>

        </div>
      </body>

    </html>
  );
}
